### ISSUE TITLE
Script Error MenuV

### ISSUE THREAD

**Issue by KshitijKalambe** [SovietRulez/SBShops#2]
![FiveM - Crikes Roleplay built with QBCore Framework by JericoFx   Kakarot   Hamy! 30-09-2021 19_16_57 (2)](https://user-images.githubusercontent.com/88702135/135491175-d268cba7-94d7-4de5-b93f-278d5b752e9e.png)

getting error also this 

![FiveM - Crikes Roleplay built with QBCore Framework by JericoFx   Kakarot   Hamy! 30-09-2021 19_16_57 (3)](https://user-images.githubusercontent.com/88702135/135491579-ff78c32c-0b8c-44de-94e4-285149775a79.png)
linden_outlawalert is esx if there is qbcore version please tell me.

**Comment by SovietRulez** [comment]
You need to use the linden alert that is converted to qbcore. Look on GhzGarage github.

As for the other issue, I do not have IsLoaded within SBShops so there is an underlying issue within ur server there.

**Comment by KshitijKalambe** [comment]
oops sorry menuv was starting after sbshops, sorry for trouble
